"""add allow_permanent_deletion to tenants

Revision ID: 08b741f0786f
Revises: 1d367beeb000
Create Date: 2026-07-29 20:08:09.367842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b741f0786f'
down_revision: Union[str, Sequence[str], None] = '1d367beeb000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_expenses_tenant_status', 'expenses', ['tenant_id', 'status'], unique=False, if_not_exists=True)
    op.create_index('idx_receipts_tenant_date', 'receipts', ['tenant_id', 'receipt_date'], unique=False, if_not_exists=True)
    op.create_index('idx_receipts_tenant_status', 'receipts', ['tenant_id', 'status'], unique=False, if_not_exists=True)
    op.create_foreign_key('fk_receipts_settlement_id', 'receipts', 'cash_settlements', ['settlement_id'], ['id'], ondelete='SET NULL')
    op.add_column('tenants', sa.Column('allow_permanent_deletion', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'allow_permanent_deletion')
    op.drop_constraint('fk_receipts_settlement_id', 'receipts', type_='foreignkey')
    op.drop_index('idx_receipts_tenant_status', table_name='receipts')
    op.drop_index('idx_receipts_tenant_date', table_name='receipts')
    op.drop_index('idx_expenses_tenant_status', table_name='expenses')
    # ### end Alembic commands ###
