"""add_receipt_template

Revision ID: 1d367beeb000
Revises: a5174ed0f085
Create Date: 2026-07-27 14:00:49.041303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d367beeb000'
down_revision: Union[str, Sequence[str], None] = 'a5174ed0f085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('receipt_template', sa.String(length=50), server_default='modern', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'receipt_template')
    # ### end Alembic commands ###
