"""add_user_invitations_table

Revision ID: 5a69ec628dc2
Revises: b7e9f1a2c3d4
Create Date: 2026-07-31 20:38:07.405058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a69ec628dc2'
down_revision: Union[str, Sequence[str], None] = 'b7e9f1a2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_checkouts', 'damage_charge',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint(op.f('asset_checkouts_asset_id_fkey'), 'asset_checkouts', type_='foreignkey')
    op.create_foreign_key(None, 'asset_checkouts', 'assets', ['asset_id'], ['id'])
    op.alter_column('assets', 'estimated_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint(op.f('assets_category_id_fkey'), 'assets', type_='foreignkey')
    op.drop_constraint(op.f('assets_festival_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'asset_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'assets', 'festivals', ['festival_id'], ['id'])
    op.create_index('idx_expenses_tenant_status', 'expenses', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_receipts_tenant_date', 'receipts', ['tenant_id', 'receipt_date'], unique=False)
    op.create_index('idx_receipts_tenant_status', 'receipts', ['tenant_id', 'status'], unique=False)
    op.create_foreign_key(None, 'receipts', 'cash_settlements', ['settlement_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tenants', 'allow_permanent_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenants', 'ai_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'gemini'::character varying"))
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tenants', 'ai_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'gemini'::character varying"))
    op.alter_column('tenants', 'allow_permanent_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index('idx_receipts_tenant_status', table_name='receipts')
    op.drop_index('idx_receipts_tenant_date', table_name='receipts')
    op.drop_index('idx_expenses_tenant_status', table_name='expenses')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_festival_id_fkey'), 'assets', 'festivals', ['festival_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('assets_category_id_fkey'), 'assets', 'asset_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('assets', 'estimated_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint(None, 'asset_checkouts', type_='foreignkey')
    op.create_foreign_key(op.f('asset_checkouts_asset_id_fkey'), 'asset_checkouts', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('asset_checkouts', 'damage_charge',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###
