"""add_soft_delete_and_schema_updates

Revision ID: 857755916b79
Revises: a0fd9da3682a
Create Date: 2026-08-03 17:20:25.258999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857755916b79'
down_revision: Union[str, Sequence[str], None] = 'a0fd9da3682a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE donors ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE donors ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL")
    op.execute("CREATE INDEX IF NOT EXISTS ix_donors_is_deleted ON donors (is_deleted)")

    op.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL")
    op.execute("CREATE INDEX IF NOT EXISTS ix_expenses_is_deleted ON expenses (is_deleted)")

    op.execute("ALTER TABLE receipts ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE receipts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL")
    op.execute("CREATE INDEX IF NOT EXISTS ix_receipts_is_deleted ON receipts (is_deleted)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_is_deleted'), table_name='receipts')
    op.drop_column('receipts', 'deleted_at')
    op.drop_column('receipts', 'is_deleted')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_column('expenses', 'deleted_at')
    op.drop_column('expenses', 'is_deleted')
    op.drop_index(op.f('ix_donors_is_deleted'), table_name='donors')
    op.drop_column('donors', 'deleted_at')
    op.drop_column('donors', 'is_deleted')
    # ### end Alembic commands ###
