"""add_soft_delete_and_schema_updates

Revision ID: 857755916b79
Revises: a0fd9da3682a
Create Date: 2026-08-03 17:20:25.258999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857755916b79'
down_revision: Union[str, Sequence[str], None] = 'a0fd9da3682a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('donors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_donors_is_deleted'), 'donors', ['is_deleted'], unique=False)
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('expenses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.add_column('receipts', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('receipts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_receipts_is_deleted'), 'receipts', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_is_deleted'), table_name='receipts')
    op.drop_column('receipts', 'deleted_at')
    op.drop_column('receipts', 'is_deleted')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_column('expenses', 'deleted_at')
    op.drop_column('expenses', 'is_deleted')
    op.drop_index(op.f('ix_donors_is_deleted'), table_name='donors')
    op.drop_column('donors', 'deleted_at')
    op.drop_column('donors', 'is_deleted')
    # ### end Alembic commands ###
