"""receipt_number_tenant_scoped_unique

Revision ID: a0fd9da3682a
Revises: 5a69ec628dc2
Create Date: 2026-08-03 16:36:24.503016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0fd9da3682a'
down_revision: Union[str, Sequence[str], None] = '5a69ec628dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_invitation_templates_tenant_id'), table_name='ai_invitation_templates')
    op.drop_table('ai_invitation_templates')
    op.create_index('idx_donors_tenant_phone', 'donors', ['tenant_id', 'phone'], unique=False)
    op.create_index(op.f('ix_donors_phone'), 'donors', ['phone'], unique=False)
    op.drop_column('event_invitations', 'artwork_url')
    op.drop_column('event_invitations', 'audio_url')
    op.create_index('idx_expenses_tenant_status_date', 'expenses', ['tenant_id', 'status', 'expense_date'], unique=False)
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=False)
    op.create_index('idx_receipts_tenant_mode_status', 'receipts', ['tenant_id', 'payment_mode', 'status'], unique=False)
    op.create_index('idx_receipts_tenant_status_date', 'receipts', ['tenant_id', 'status', 'receipt_date'], unique=False)
    op.create_unique_constraint('uq_receipts_tenant_receipt_number', 'receipts', ['tenant_id', 'receipt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_receipts_tenant_receipt_number', 'receipts', type_='unique')
    op.drop_index('idx_receipts_tenant_status_date', table_name='receipts')
    op.drop_index('idx_receipts_tenant_mode_status', table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.drop_index('idx_expenses_tenant_status_date', table_name='expenses')
    op.add_column('event_invitations', sa.Column('audio_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('event_invitations', sa.Column('artwork_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_donors_phone'), table_name='donors')
    op.drop_index('idx_donors_tenant_phone', table_name='donors')
    op.create_table('ai_invitation_templates',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('festival', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('illustration', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('paper', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('card_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('invitation_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('ai_invitation_templates_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('ai_invitation_templates_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_invitation_templates_pkey'))
    )
    op.create_index(op.f('ix_ai_invitation_templates_tenant_id'), 'ai_invitation_templates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
