"""Add qr_code_url and upi_id to Tenant

Revision ID: a5174ed0f085
Revises: 6d3b1d53e9d5
Create Date: 2026-07-27 13:18:40.363432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5174ed0f085'
down_revision: Union[str, Sequence[str], None] = '6d3b1d53e9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('upi_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'upi_id')
    op.drop_column('tenants', 'qr_code_url')
    # ### end Alembic commands ###
